services:
  flask:
    build: ./flask
    container_name: imdb-flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  express:
    build: ./express
    container_name: imdb-express
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  springboot:
    build: ./springboot
    container_name: imdb-springboot
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
